app = 'futbol-web'
primary_region = 'mia'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  # DATABASE_URL se inyecta automaticamente por Fly al hacer postgres attach

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
